services:
  server:
    build: .
    image: server
    env_file:
      - ./server/.env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - kilimboga

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - kilimboga

volumes:
  dbdata:

networks:
  kilimboga:
    driver: bridge
